name: RAYS Build

on: push

jobs:
  build:
    runs-on: ${{matrix.os}}

  strategy: 
    matrix:
      os: [macos-latest, ubuntu-latest, windows-latest]

  steps:
    - name: "Install g++-multilib"
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt update && sudo apt install g++-multilib

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.14.1'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run dist