name: Build RAYS Client

on: push

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install g++-multilib
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install g++-multilib

      - name: Install python
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.16.3'

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npx electron compile

      - name: Build
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}