name: Build RAYS Client

on: push

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install g++-multilib
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install g++-multilib

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npx electron compile

      - name: Build
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}