name: Build RAYS Client (Ubuntu)

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install g++-multilib
        run: sudo apt update && sudo apt install g++-multilib

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.12.1'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}